package com.dollhousestudio.websocket.websocket.connect.Websocket.connect

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsConnectMethodIDL : AbsSparklingIDLMethod<AbsConnectMethodIDL.IDLMethodConnectInputModel, AbsConnectMethodIDL.IDLMethodConnectResultModel>() {

    @IDLMethodName(name = "Websocket.connect", params = ["url", "protocols"], results = ["code", "msg", "data"])
    final override val name: String = "Websocket.connect"

    @IDLMethodParamModel
    interface IDLMethodConnectInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "url")
        val url: String 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "protocols", primitiveClassType = String::class)
        val protocols: List<String>? 
    }

    @IDLMethodResultModel
    interface IDLMethodConnectResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "code")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "code")
        var code: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "msg")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "msg")
        var msg: String? 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "data", nestedClassType = PipeBeanConnectData::class)
        @set:IDLMethodParamField(required = false, isGetter = false, keyPath = "data", nestedClassType = PipeBeanConnectData::class)
        var data: PipeBeanConnectData? 
    }

    interface PipeBeanConnectData : IDLMethodBaseModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "socketId")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "socketId")
        var socketId: String? 
    }
}
