package com.dollhousestudio.websocket.websocket.send.Websocket.send

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsSendMethodIDL : AbsSparklingIDLMethod<AbsSendMethodIDL.IDLMethodSendInputModel, AbsSendMethodIDL.IDLMethodSendResultModel>() {

    @IDLMethodName(name = "Websocket.send", params = ["socketId", "data"], results = ["code", "msg"])
    final override val name: String = "Websocket.send"

    @IDLMethodParamModel
    interface IDLMethodSendInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "socketId")
        val socketId: String 

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "data")
        val data: String 
    }

    @IDLMethodResultModel
    interface IDLMethodSendResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "code")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "code")
        var code: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "msg")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "msg")
        var msg: String? 
    }
}
