package com.dollhousestudio.websocket.websocket.close.Websocket.close

import com.tiktok.sparkling.method.registry.core.annotation.DefaultType
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodIntEnum
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodName
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamField
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodParamModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodResultModel
import com.tiktok.sparkling.method.registry.core.annotation.IDLMethodStringEnum
import com.tiktok.sparkling.method.registry.core.annotation.MethodParamDefaultValue
import com.tiktok.sparkling.method.registry.core.base.AbsSparklingIDLMethod
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseParamModel
import com.tiktok.sparkling.method.registry.core.model.idl.IDLMethodBaseResultModel


/**
 * GENERATED BY SPARKLING METHOD CLI.
 */
 
abstract class AbsCloseMethodIDL : AbsSparklingIDLMethod<AbsCloseMethodIDL.IDLMethodCloseInputModel, AbsCloseMethodIDL.IDLMethodCloseResultModel>() {

    @IDLMethodName(name = "Websocket.close", params = ["socketId", "code", "reason"], results = ["code", "msg"])
    final override val name: String = "Websocket.close"

    @IDLMethodParamModel
    interface IDLMethodCloseInputModel : IDLMethodBaseParamModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "socketId")
        val socketId: String 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "code")
        val code: Number? 

        @get:IDLMethodParamField(required = false, isGetter = true, keyPath = "reason")
        val reason: String? 
    }

    @IDLMethodResultModel
    interface IDLMethodCloseResultModel: IDLMethodBaseResultModel {

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "code")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "code")
        var code: Number? // you can't set a Number type to this param, only support Int/Double/Long/Float

        @get:IDLMethodParamField(required = true, isGetter = true, keyPath = "msg")
        @set:IDLMethodParamField(required = true, isGetter = false, keyPath = "msg")
        var msg: String? 
    }
}
